# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'GitHubSearchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubSearchApp
  pod 'ReactComponentKit'
  pod 'BKEventBus'
  pod 'BKRouter'
  pod 'SnapKit'
  pod 'Moya'
  pod 'Kingfisher'
  pod 'YYWebImage'
  
  target 'GitHubSearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

